import { useEffect, useMemo, useState } from "react";
import { CalendarIcon, CheckCircledIcon, ChevronDownIcon, ChevronLeftIcon, ChevronRightIcon, Cross2Icon, GearIcon, HomeIcon, MagnifyingGlassIcon, PlusIcon, ReaderIcon } from "@radix-ui/react-icons";
import "@fontsource/fraunces/600.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import { BottomSheet, KeyboardInput, MobileScroll, useKeyboard } from "./web";

type Subtask = { id:string; title:string; completed:boolean };
type TaskList = "Personal"|"Work"|"Shopping";
type Task = { id:string; title:string; notes?:string; time?:string; date?:string; list?:TaskList; subtasks?:Subtask[]; progress:number; completed:boolean; section:"scheduled"|"anytime" };
const DB_NAME="plan-it-v2", STORE="tasks";
function openDb(){ return new Promise<IDBDatabase>((resolve,reject)=>{ const request=indexedDB.open(DB_NAME,1); request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:"id"}); request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error); }); }
async function loadTasks(){ const db=await openDb(); return new Promise<Task[]>((resolve,reject)=>{ const request=db.transaction(STORE).objectStore(STORE).getAll(); request.onsuccess=()=>resolve(request.result as Task[]); request.onerror=()=>reject(request.error); }); }
async function saveTasks(tasks:Task[]){ const db=await openDb(); const tx=db.transaction(STORE,"readwrite"); const store=tx.objectStore(STORE); store.clear(); tasks.forEach((task)=>store.put(task)); }
function toLocalIso(date:Date){ const local=new Date(date.getTime()-date.getTimezoneOffset()*60_000); return local.toISOString().slice(0,10); }
function formatLongDate(value:string){ return new Intl.DateTimeFormat("en-US",{weekday:"long",month:"short",day:"numeric"}).format(new Date(`${value}T12:00:00`)); }
function weekFor(value:string){ const selected=new Date(`${value}T12:00:00`); const sunday=new Date(selected); sunday.setDate(selected.getDate()-selected.getDay()); return Array.from({length:7},(_,index)=>{const date=new Date(sunday);date.setDate(sunday.getDate()+index);return {iso:toLocalIso(date),day:new Intl.DateTimeFormat("en-US",{weekday:"short"}).format(date),number:String(date.getDate())};}); }
function monthDays(value:Date){ const year=value.getFullYear(),month=value.getMonth(),firstDay=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate(); return [...Array.from({length:firstDay},()=>null),...Array.from({length:days},(_,index)=>{const date=new Date(year,month,index+1,12);return {iso:toLocalIso(date),number:index+1};})]; }
function taskList(task:Task):TaskList{ if(task.list)return task.list; if(task.id==="groceries")return "Shopping"; if(task.id==="proposal"||task.id==="budget")return "Work"; return "Personal"; }
function greetingFor(date=new Date()){ const hour=date.getHours(); return hour<12?"Good morning":hour<17?"Good afternoon":"Good evening"; }
function useGreeting(){ const [greeting,setGreeting]=useState(()=>greetingFor()); useEffect(()=>{const timer=window.setInterval(()=>setGreeting(greetingFor()),60_000);return()=>window.clearInterval(timer);},[]); return greeting; }

function Onboarding({onComplete}:{onComplete:(name:string)=>void}){
  const [name,setName]=useState(""); const keyboard=useKeyboard(); const greeting=useGreeting();
  const finish=(value:string)=>{(document.activeElement as HTMLElement|null)?.blur();keyboard.hide();onComplete(value);};
  return <MobileScroll className="app-screen onboarding-scroll"><main className="onboarding" aria-label="Plan-it onboarding">
    <header className="onboarding-top"><div className="wordmark">Plan-it<span>.</span></div><div className="stepper"><span>1 of 3</span><i className="active"/><i/><i/></div></header>
    <section className="onboarding-copy"><h1>Let’s make<br/>it yours</h1><p>What should we call you?</p></section>
    <label className="name-field"><span>First name</span><KeyboardInput value={name} onChange={(event)=>setName(event.target.value)} aria-label="First name"/></label>
    <div className="greeting-preview"><span>Your home will say:</span><strong>{greeting}, {name.trim()||"there"}</strong></div>
    <div className="onboarding-actions"><button className="primary-button" onClick={()=>finish(name.trim()||"there")}>Continue</button><button className="text-button" onClick={()=>finish("there")}>Skip for now</button></div>
    <p className="offline-note"><CheckCircledIcon/> Your preferences are saved on this device.</p>
  </main></MobileScroll>;
}
function ProgressBar({value,segmented=false}:{value:number;segmented?:boolean}){ return segmented ? <div className="segmented-progress" aria-label={`${value}% complete`}>{[20,40,60,80,100].map((point)=><i key={point} className={point<=value?"filled":""}/>)}</div> : <div className="progress-track" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${value}%`}}/></div>; }
function TaskRow({task,onToggle,onOpen}:{task:Task;onToggle:()=>void;onOpen:()=>void}){ const done=task.subtasks?.filter((item)=>item.completed).length??0; return <article className={`task-row ${task.completed?"is-complete":""}`}>
  <time className={task.time?"":"no-time"}>{task.time??""}</time><button className="task-check" onClick={onToggle} aria-label={task.completed?`Reopen ${task.title}`:`Complete ${task.title}`}>{task.completed&&<CheckCircledIcon/>}</button>
  <button className="task-main" onClick={onOpen}><span className="task-title">{task.title}</span>{task.progress>0&&task.progress<100&&<span className="task-progress-line"><ProgressBar value={task.progress} segmented={Boolean(task.subtasks?.length)||task.id==="budget"}/><b>{task.subtasks?.length?`${done} of ${task.subtasks.length} subtasks`:task.id==="budget"?"3 of 5 subtasks":`${task.progress}%`}</b></span>}{task.notes&&<small>{task.notes}</small>}{task.subtasks?.length&&task.progress===0?<small>{task.subtasks.length} {task.subtasks.length===1?"subtask":"subtasks"}</small>:null}</button><ChevronRightIcon className="row-chevron"/>
</article>; }
function TaskSection({title,tasks,onToggle,onOpen}:{title:string;tasks:Task[];onToggle:(id:string)=>void;onOpen:(task:Task)=>void}){ const [expanded,setExpanded]=useState(true); return <section className={`task-section ${expanded?"":"collapsed"}`}><header><button onClick={()=>setExpanded((value)=>!value)} aria-expanded={expanded}><h2>{title}</h2><span>{tasks.length} {tasks.length===1?"task":"tasks"}</span><ChevronDownIcon/></button></header>{expanded&&(tasks.length?tasks.map((task)=><TaskRow key={task.id} task={task} onToggle={()=>onToggle(task.id)} onOpen={()=>onOpen(task)}/>):<p className="empty-row">Nothing here yet.</p>)}</section>; }

function ScreenHeader({eyebrow,title,detail}:{eyebrow:string;title:string;detail:string}){ return <header className="screen-header"><p>{eyebrow}</p><h1>{title}</h1><span>{detail}</span></header>; }
function UpcomingView({tasks,today,onToggle,onOpen,onPlan}:{tasks:Task[];today:string;onToggle:(id:string)=>void;onOpen:(task:Task)=>void;onPlan:()=>void}){
  const groups=useMemo(()=>{const future=tasks.filter((task)=>!task.completed&&(task.date??today)>today).sort((a,b)=>(a.date??today).localeCompare(b.date??today)||(a.time??"99:99").localeCompare(b.time??"99:99"));return future.reduce<Record<string,Task[]>>((all,task)=>{const date=task.date??today;(all[date]??=[]).push(task);return all;},{});},[tasks,today]);
  const dates=Object.keys(groups); return <MobileScroll className="app-screen today-scroll"><main className="tab-content"><ScreenHeader eyebrow="Your schedule" title="Upcoming" detail={dates.length?`${dates.length} upcoming ${dates.length===1?"day":"days"}`:"Nothing planned yet"}/>{dates.length?<div className="upcoming-groups">{dates.map((date)=><section className="upcoming-group" key={date}><header><div><strong>{new Intl.DateTimeFormat("en-US",{weekday:"long"}).format(new Date(`${date}T12:00:00`))}</strong><span>{new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric"}).format(new Date(`${date}T12:00:00`))}</span></div><b>{groups[date].length}</b></header>{groups[date].map((task)=><TaskRow key={task.id} task={task} onToggle={()=>onToggle(task.id)} onOpen={()=>onOpen(task)}/>)}</section>)}</div>:<div className="empty-state"><CalendarIcon/><h2>Your future is wide open</h2><p>Add a task to any future date and it will appear here.</p><button className="primary-button" onClick={onPlan}>Plan something</button></div>}</main></MobileScroll>;
}
function ListsView({tasks,onToggle,onOpen}:{tasks:Task[];onToggle:(id:string)=>void;onOpen:(task:Task)=>void}){
  const [selected,setSelected]=useState<string|null>(null); const listNames:TaskList[]=["Personal","Work","Shopping"]; const visible=selected==="All tasks"?tasks:selected==="Scheduled"?tasks.filter((task)=>task.section==="scheduled"):selected==="Completed"?tasks.filter((task)=>task.completed):selected?tasks.filter((task)=>taskList(task)===selected):[];
  if(selected)return <MobileScroll className="app-screen today-scroll"><main className="tab-content"><button className="screen-back" onClick={()=>setSelected(null)}><ChevronLeftIcon/> All lists</button><ScreenHeader eyebrow="List" title={selected} detail={`${visible.length} ${visible.length===1?"task":"tasks"}`}/><section className="plain-task-list">{visible.length?visible.map((task)=><TaskRow key={task.id} task={task} onToggle={()=>onToggle(task.id)} onOpen={()=>onOpen(task)}/>):<p className="empty-row">No tasks in this list yet.</p>}</section></main></MobileScroll>;
  return <MobileScroll className="app-screen today-scroll"><main className="tab-content"><ScreenHeader eyebrow="Stay organized" title="Lists" detail="Everything has its place"/><section className="smart-list-grid"><button onClick={()=>setSelected("All tasks")}><span className="list-icon purple"><ReaderIcon/></span><strong>All tasks</strong><small>{tasks.length}</small></button><button onClick={()=>setSelected("Scheduled")}><span className="list-icon teal"><CalendarIcon/></span><strong>Scheduled</strong><small>{tasks.filter((task)=>task.section==="scheduled").length}</small></button><button onClick={()=>setSelected("Completed")}><span className="list-icon plum"><CheckCircledIcon/></span><strong>Completed</strong><small>{tasks.filter((task)=>task.completed).length}</small></button></section><h2 className="section-label">My lists</h2><section className="my-lists">{listNames.map((list,index)=><button key={list} onClick={()=>setSelected(list)}><i className={`list-dot dot-${index}`}/><span><strong>{list}</strong><small>{tasks.filter((task)=>taskList(task)===list).length} tasks</small></span><ChevronRightIcon/></button>)}</section></main></MobileScroll>;
}
function SearchView({tasks,onToggle,onOpen}:{tasks:Task[];onToggle:(id:string)=>void;onOpen:(task:Task)=>void}){
  const [query,setQuery]=useState(""); const normalized=query.trim().toLowerCase(); const results=normalized?tasks.filter((task)=>[task.title,task.notes,...(task.subtasks??[]).map((item)=>item.title)].some((value)=>value?.toLowerCase().includes(normalized))):[];
  return <MobileScroll className="app-screen today-scroll"><main className="tab-content search-screen"><ScreenHeader eyebrow="Find anything" title="Search" detail="Tasks, notes and subtasks"/><label className="search-field"><MagnifyingGlassIcon/><KeyboardInput value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search your tasks…" aria-label="Search tasks"/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear search"><Cross2Icon/></button>}</label>{normalized?<><div className="result-count">{results.length} {results.length===1?"result":"results"}</div><section className="plain-task-list search-results">{results.length?results.map((task)=><div className="search-result" key={task.id}><TaskRow task={task} onToggle={()=>onToggle(task.id)} onOpen={()=>onOpen(task)}/><div className="result-meta"><span>{taskList(task)}</span><span>{task.date?formatLongDate(task.date):"Today"}</span></div></div>):<div className="empty-state compact"><MagnifyingGlassIcon/><h2>No matches found</h2><p>Try a task title, note, or subtask.</p></div>}</section></>:<div className="search-hint"><MagnifyingGlassIcon/><p>Start typing to search everything you’ve planned.</p></div>}</main></MobileScroll>;
}
function SettingsView({name,defaultList,tasks,onSave}:{name:string;defaultList:TaskList;tasks:Task[];onSave:(name:string,list:TaskList)=>void}){
  const keyboard=useKeyboard(); const [draftName,setDraftName]=useState(name); const [draftList,setDraftList]=useState<TaskList>(defaultList); const [saved,setSaved]=useState(false);
  const save=()=>{const nextName=draftName.trim()||"there";(document.activeElement as HTMLElement|null)?.blur();keyboard.hide();onSave(nextName,draftList);setDraftName(nextName);setSaved(true);window.setTimeout(()=>setSaved(false),1800);};
  const exportData=()=>{const payload={app:"Plan-it",exportedAt:new Date().toISOString(),profile:{name,defaultList},tasks};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`plan-it-backup-${toLocalIso(new Date())}.json`;anchor.click();URL.revokeObjectURL(url);};
  return <MobileScroll className="app-screen today-scroll"><main className="tab-content settings-screen"><ScreenHeader eyebrow="Make it yours" title="Settings" detail="Preferences stay on this device"/><section className="settings-card"><h2>Profile</h2><label><span>Your name</span><KeyboardInput value={draftName} onChange={(event)=>setDraftName(event.target.value)} aria-label="Your name"/></label><label><span>Default list</span><select value={draftList} onChange={(event)=>setDraftList(event.target.value as TaskList)} aria-label="Default task list"><option>Personal</option><option>Work</option><option>Shopping</option></select></label><button className="primary-button" onClick={save}>{saved?"Saved ✓":"Save preferences"}</button></section><section className="settings-card storage-card"><div className="settings-card-heading"><span className="list-icon teal"><CheckCircledIcon/></span><div><h2>Offline storage</h2><p>{tasks.length} tasks saved on this device</p></div></div><div className="storage-status"><i/><span>Available offline</span></div><button className="secondary-button" onClick={exportData}>Export JSON backup</button></section><p className="settings-note">Plan-it currently stores your tasks locally. Cloud sync can be added later without changing this workflow.</p></main></MobileScroll>;
}

function TodayScreen({name,onNameChange}:{name:string;onNameChange:(name:string)=>void}){
  const today=toLocalIso(new Date()); const keyboard=useKeyboard(); const greeting=useGreeting(); const [tasks,setTasks]=useState<Task[]>([]); const [loaded,setLoaded]=useState(false); const [draft,setDraft]=useState(""); const [newTaskTime,setNewTaskTime]=useState(""); const [defaultList,setDefaultList]=useState<TaskList>(()=>(localStorage.getItem("plan-it-default-list") as TaskList)||"Personal"); const [newTaskList,setNewTaskList]=useState<TaskList>(defaultList); const [subtaskDraft,setSubtaskDraft]=useState(""); const [newSubtasks,setNewSubtasks]=useState<Subtask[]>([]); const [addOpen,setAddOpen]=useState(false); const [calendarOpen,setCalendarOpen]=useState(false); const [calendarMonth,setCalendarMonth]=useState(()=>new Date(`${today}T12:00:00`)); const [sheetOpen,setSheetOpen]=useState(false); const [activeTask,setActiveTask]=useState<Task|null>(null); const [selectedDate,setSelectedDate]=useState(today); const [tab,setTab]=useState("Today"); const [completedOpen,setCompletedOpen]=useState(false);
  useEffect(()=>{loadTasks().then(setTasks).finally(()=>setLoaded(true));},[]);
  useEffect(()=>{if(loaded) void saveTasks(tasks);},[tasks,loaded]);
  const datedTasks=useMemo(()=>tasks.filter((task)=>(task.date??today)===selectedDate),[tasks,selectedDate,today]); const active=datedTasks.filter((task)=>!task.completed); const complete=datedTasks.filter((task)=>task.completed); const scheduled=active.filter((task)=>task.section==="scheduled").sort((a,b)=>Number((a.time??"0").replace(":",""))-Number((b.time??"0").replace(":",""))); const anytimeOrder=new Map([["groceries",0],["budget",1]]); const anytime=active.filter((task)=>task.section==="anytime").sort((a,b)=>(anytimeOrder.get(a.id)??99)-(anytimeOrder.get(b.id)??99)); const week=weekFor(selectedDate);
  const beginAdd=()=>{if(!draft.trim())return;(document.activeElement as HTMLElement|null)?.blur();keyboard.hide();setAddOpen(true);};
  const openCalendar=()=>{keyboard.hide();setCalendarMonth(new Date(`${selectedDate}T12:00:00`));setCalendarOpen(true);};
  const selectDate=(iso:string)=>{if(iso<today)return;setSelectedDate(iso);setCalendarOpen(false);};
  const appendSubtask=()=>{const title=subtaskDraft.trim();if(!title)return;setNewSubtasks((current)=>[...current,{id:crypto.randomUUID(),title,completed:false}]);setSubtaskDraft("");};
  const addTask=()=>{const title=draft.trim(); if(!title)return; setTasks((current)=>[...current,{id:crypto.randomUUID(),title,date:selectedDate,time:newTaskTime||undefined,list:newTaskList,subtasks:newSubtasks,progress:0,completed:false,section:newTaskTime?"scheduled":"anytime"}]); setDraft(""); setNewTaskTime(""); setNewTaskList(defaultList); setSubtaskDraft(""); setNewSubtasks([]); setAddOpen(false); keyboard.hide();};
  const saveSettings=(nextName:string,list:TaskList)=>{localStorage.setItem("plan-it-name",nextName);localStorage.setItem("plan-it-default-list",list);setDefaultList(list);setNewTaskList(list);onNameChange(nextName);};
  const toggle=(id:string)=>setTasks((current)=>current.map((task)=>task.id===id?{...task,completed:!task.completed,progress:task.completed?Math.min(task.progress,95):100}:task));
  const updateProgress=(value:number)=>{if(!activeTask)return; setTasks((current)=>current.map((task)=>task.id===activeTask.id?{...task,progress:value,completed:value===100}:task)); setActiveTask((task)=>task?{...task,progress:value,completed:value===100}:null);};
  const toggleSubtask=(subtaskId:string)=>{if(!activeTask)return;const update=(task:Task)=>{const subtasks=(task.subtasks??[]).map((item)=>item.id===subtaskId?{...item,completed:!item.completed}:item);const completeCount=subtasks.filter((item)=>item.completed).length;const progress=subtasks.length?Math.round(completeCount/subtasks.length*100):task.progress;return {...task,subtasks,progress,completed:progress===100};};setTasks((current)=>current.map((task)=>task.id===activeTask.id?update(task):task));setActiveTask((task)=>task?update(task):null);};
  const openTask=(task:Task)=>{(document.activeElement as HTMLElement|null)?.blur();keyboard.hide();setActiveTask(task);setSheetOpen(true);};
  return <div className="today-shell">{tab==="Today"&&<MobileScroll className="app-screen today-scroll"><main className="today-content" aria-label="Plan-it Today">
    <header className="today-header"><div><p>{greeting}, {name}</p><h1>{selectedDate===today?"Today":"Schedule"}</h1><time>{formatLongDate(selectedDate)}</time></div><span className="save-state"><CheckCircledIcon/> Saved offline</span></header>
    <form className="quick-add" onSubmit={(event)=>{event.preventDefault();beginAdd();}}><KeyboardInput value={draft} onChange={(event)=>setDraft(event.target.value)} placeholder="Add a task…" aria-label="Add a task"/><button type="submit" aria-label="Continue adding task"><PlusIcon/></button></form>
    <div className="week-strip" aria-label={`Week containing ${formatLongDate(selectedDate)}`}>{week.map(({iso,day,number})=><button key={iso} className={iso===selectedDate?"selected":""} onClick={()=>selectDate(iso)} aria-pressed={iso===selectedDate} disabled={iso<today}><span>{day}</span><b>{number}</b></button>)}</div>
    <button className="full-calendar-button" onClick={openCalendar}><CalendarIcon/><span>Full calendar</span><ChevronRightIcon/></button>
    <TaskSection title="Scheduled" tasks={scheduled} onToggle={toggle} onOpen={openTask}/><TaskSection title="Anytime" tasks={anytime} onToggle={toggle} onOpen={openTask}/>
    <section className="completed-section"><button onClick={()=>setCompletedOpen((value)=>!value)}><ChevronDownIcon className={completedOpen?"rotated":""}/><strong>Completed</strong><span>{complete.length}</span></button>{completedOpen&&complete.map((task)=><TaskRow key={task.id} task={task} onToggle={()=>toggle(task.id)} onOpen={()=>openTask(task)}/>)}</section>
  </main></MobileScroll>}
  {tab==="Upcoming"&&<UpcomingView tasks={tasks} today={today} onToggle={toggle} onOpen={openTask} onPlan={()=>{setSelectedDate(today);setTab("Today");openCalendar();}}/>}
  {tab==="Lists"&&<ListsView tasks={tasks} onToggle={toggle} onOpen={openTask}/>} 
  {tab==="Search"&&<SearchView tasks={tasks} onToggle={toggle} onOpen={openTask}/>} 
  {tab==="Settings"&&<SettingsView name={name} defaultList={defaultList} tasks={tasks} onSave={saveSettings}/>} 
  <nav className="bottom-nav" aria-label="Primary navigation">{[["Today",HomeIcon],["Upcoming",CalendarIcon],["Lists",ReaderIcon],["Search",MagnifyingGlassIcon],["Settings",GearIcon]].map(([label,Icon])=><button key={label as string} className={tab===label?"active":""} onClick={()=>setTab(label as string)}><Icon/><span>{label as string}</span></button>)}</nav>
  <BottomSheet open={calendarOpen} onOpenChange={setCalendarOpen} title="Choose a date" description="Plan as far ahead as you like"><div className="calendar-sheet"><div className="calendar-toolbar"><button onClick={()=>setCalendarMonth((current)=>new Date(current.getFullYear(),current.getMonth()-1,1,12))} disabled={calendarMonth.getFullYear()===new Date().getFullYear()&&calendarMonth.getMonth()===new Date().getMonth()} aria-label="Previous month"><ChevronLeftIcon/></button><strong>{new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric"}).format(calendarMonth)}</strong><button onClick={()=>setCalendarMonth((current)=>new Date(current.getFullYear(),current.getMonth()+1,1,12))} aria-label="Next month"><ChevronRightIcon/></button></div><div className="calendar-weekdays">{["S","M","T","W","T","F","S"].map((day,index)=><span key={`${day}-${index}`}>{day}</span>)}</div><div className="calendar-grid">{monthDays(calendarMonth).map((day,index)=>day?<button key={day.iso} className={day.iso===selectedDate?"selected":""} disabled={day.iso<today} onClick={()=>selectDate(day.iso)} aria-label={formatLongDate(day.iso)} aria-pressed={day.iso===selectedDate}>{day.number}</button>:<i key={`blank-${index}`}/>)}</div><button className="calendar-today" onClick={()=>selectDate(today)}>Jump to today</button></div></BottomSheet>
  <BottomSheet open={addOpen} onOpenChange={setAddOpen} title="New task" description={`For ${formatLongDate(selectedDate)}`}><div className="task-sheet add-task-sheet"><label><span>Task</span><KeyboardInput value={draft} onChange={(event)=>setDraft(event.target.value)} aria-label="Task title"/></label><label><span>List</span><select value={newTaskList} onChange={(event)=>setNewTaskList(event.target.value as TaskList)} aria-label="Task list"><option>Personal</option><option>Work</option><option>Shopping</option></select></label><label><span>Time <em>Optional</em></span><input type="time" value={newTaskTime} onChange={(event)=>setNewTaskTime(event.target.value)} aria-label="Task time"/><small>{newTaskTime?"This task will appear under Scheduled.":"No time means it will appear under Anytime."}</small></label><div className="subtask-heading"><strong>Subtasks</strong><span>Optional</span></div><form className="subtask-add" onSubmit={(event)=>{event.preventDefault();appendSubtask();}}><KeyboardInput value={subtaskDraft} onChange={(event)=>setSubtaskDraft(event.target.value)} placeholder="Add a smaller step…" aria-label="New subtask"/><button type="submit" aria-label="Add subtask"><PlusIcon/></button></form>{newSubtasks.length>0&&<ul className="new-subtask-list">{newSubtasks.map((item)=><li key={item.id}><span>{item.title}</span><button onClick={()=>setNewSubtasks((current)=>current.filter((candidate)=>candidate.id!==item.id))} aria-label={`Remove ${item.title}`}><Cross2Icon/></button></li>)}</ul>}<button className="primary-button" onClick={addTask}>Save task</button></div></BottomSheet>
  <BottomSheet open={sheetOpen} onOpenChange={setSheetOpen} title={activeTask?.title??"Task"} description={activeTask?.notes??"Update this task"}><div className="task-sheet">{activeTask?.subtasks?.length?<div className="subtask-checklist"><div className="subtask-heading"><strong>Subtasks</strong><span>{activeTask.subtasks.filter((item)=>item.completed).length}/{activeTask.subtasks.length}</span></div>{activeTask.subtasks.map((item)=><button key={item.id} className={item.completed?"complete":""} onClick={()=>toggleSubtask(item.id)}><i>{item.completed&&<CheckCircledIcon/>}</i><span>{item.title}</span></button>)}</div>:null}<div className="sheet-progress"><span>Progress</span><strong>{activeTask?.progress??0}%</strong></div><input type="range" min="0" max="100" step="5" value={activeTask?.progress??0} onChange={(event)=>updateProgress(Number(event.target.value))} aria-label="Task progress"/><div className="progress-presets">{[0,25,50,75,100].map((value)=><button key={value} className={activeTask?.progress===value?"active":""} onClick={()=>updateProgress(value)}>{value}%</button>)}</div><button className="primary-button" onClick={()=>{if(activeTask)toggle(activeTask.id);setSheetOpen(false);}}>{activeTask?.completed?"Reopen task":"Mark complete"}</button></div></BottomSheet>
  </div>;
}
export default function Prototype(){ const [name,setName]=useState(()=>localStorage.getItem("plan-it-name")||""); useEffect(()=>{if("serviceWorker" in navigator)void navigator.serviceWorker.register("/sw.js"); if(navigator.storage?.persist)void navigator.storage.persist();},[]); const finish=(nextName:string)=>{localStorage.setItem("plan-it-name",nextName);setName(nextName);}; return name?<TodayScreen name={name} onNameChange={setName}/>:<Onboarding onComplete={finish}/>; }
